@startuml inserimentoDatiIniziali
hide circle

skinparam class {
  BackgroundColor White
  BorderColor Black
}

class "Caso d'uso: **Inserimento dati iniziali per autenticazione**" {
  **ID**: 
  UC-07
  --
  **Attori**:
  Amministratore, Sistema
  --
  **Precondizioni**:
  1. Amministratore autenticato
  --
  **Sequenza di eventi**:
  1. Inserimento dati anagrafici di medico e paziente
  2. Verifica da parte del sistema dell'inserimento
  3. Validazione e salvataggio
  --
  **Postcondizioni**:
  1. Paziente e medico possono accedere
}
@enduml
