@startuml usercase
skinparam linetype polyline
left to right direction
actor Paziente
actor Diabetologo
actor Amministratore

rectangle "Sistema di Monitoraggio Terapeutico" {

:Paziente: -- (Registrare valori glicemici \n pre/post pasto)
:Paziente: -- (Aggiungere sintomi, patologie e/o \n terapie concomitanti)
:Paziente: -- (Inserire aderenza alla terapia)

:Diabetologo: -- (Gestire piano terapeutico)
:Diabetologo: -- (Inserire fattori di rischio, \n malattie pregresse e comorbidità)
:Diabetologo: -- (Ricevere segnalazioni \n glicemie anomale)
:Diabetologo: -- (Visualizzare dati clinici)

:Amministratore: -- (Inserire dati iniziali per autenticazione di pazienti e medici)

(Inserire aderenza alla terapia) ..> (Autenticazione utente) : <<include>>
(Aggiungere sintomi, patologie e/o \n terapie concomitanti) ..> (Autenticazione utente)
(Registrare valori glicemici \n pre/post pasto) ..> (Autenticazione utente)
(Gestire piano terapeutico) ..> (Autenticazione utente)
(Ricevere segnalazioni \n glicemie anomale) ..> (Autenticazione utente)
(Inserire fattori di rischio, \n malattie pregresse e comorbidità) ..> (Autenticazione utente)
(Visualizzare dati clinici) ..> (Autenticazione utente)



}

@enduml